version: '2'
services:
  codecept:
      image: codeception/codeception
      depends_on:
        - chrome
        - firefox
      volumes:
          - './tests:/project/tests'
          - './codeception.yml:/project/codeception.yml'
  chrome:
      image: 'selenium/standalone-chrome-debug:2.53.1'
      ports:
          - '5901:5900'
  firefox:
      image: 'selenium/standalone-firefox-debug:2.53.1'
      ports:
          - '5902:5900'
